### ISSUE TITLE
use YAML for configuration files

### ISSUE THREAD

**Issue by bigerl** [dice-group/IGUANA#96]
I find the configuration files a bit hard to read. I would suggest to use [YAML files](https://en.wikipedia.org/wiki/YAML#Example) (like in docker compose files, for example) instead which allow hierarchical configurations. That would also fit the approach of having Suits, Experiments and Tasks.

Comments are appreciated.

**Comment by tohardik** [comment]
Currently, IGUANA uses Apache's commons-configuration v1.10 (see iguana.commons/pom.xml) to load the IGUANA configuration files into Configuration class. This class has methods that make it easy to work with configuration files. An object of this class is passed around to initialize Worker, Task etc. However, commons-configuration v1.10 does not have support for YAML based configurations. 

commons-configuration 2.x has YAML support. But it has some weird dependency management. Even though v2.x has some dependencies, simply specifying v2.x in the pom does not work because v2.x [uses runtime dependencies](https://commons.apache.org/proper/commons-configuration/dependencies.html)(!!!). Additionally, the package structure in v2.x is a bit different than v1.x. See this [migration guide](https://commons.apache.org/proper/commons-configuration/userguide/upgradeto2_0.html).

Therefore, to implement this functionality:
a) List all runtime dependencies and explicitly add all of them in the pom. 
b) Make necessary changes in code (mostly changing package structure in the import statements) as suggested in the migration guide.

**Comment by TortugaAttack** [comment]
Will  be done in the next release.
 including YAML as well as JSON Support and will be validated against a JSON schema
